from __future__ import annotations

from copy import deepcopy


PRESETS: dict[str, dict] = {
    "Ethanol / Water Cooler": {
        "description": "Clean sensible-cooling service for a conventional BEM starting point.",
        "ui_state": {
            "mode_v100": "Design",
            "front_head_v100": "B",
            "shell_type_v100": "E",
            "rear_head_v100": "M",
            "thermo_package_v100": "Ideal mixture",
            "flow_arrangement_v100": "Counter-current",
            "allowable_tube_dp_v100": 70.0,
            "allowable_shell_dp_v100": 50.0,
            "hot_stream_definition": "Pure fluid",
            "hot_fluid_v100": "Ethanol",
            "hot_tin_v100": 120.0,
            "hot_p_v100": 4.0,
            "hot_flow_v100": 3.0,
            "hot_tout_v100": 70.0,
            "tube_fouling_v100": 0.0002,
            "cold_stream_definition": "Pure fluid",
            "cold_fluid_v100": "Water",
            "cold_tin_v100": 25.0,
            "cold_p_v100": 3.0,
            "cold_flow_v100": 8.0,
            "shell_fouling_v100": 0.0002,
            "wall_k_v100": 16.0,
            "shell_id_v100": 0.80,
            "tube_od_mm_v100": 19.05,
            "tube_id_mm_v100": 15.75,
            "tube_length_v100": 6.0,
            "tube_count_v100": 420,
            "tube_passes_v100": 2,
            "tube_pitch_mm_v100": 25.0,
            "tube_layout_v100": "triangular",
            "baffle_count_v100": 12,
            "baffle_cut_v100": 25,
        },
    },
    "Water / Water Training Case": {
        "description": "Simple educational liquid-liquid case with conservative geometry.",
        "ui_state": {
            "mode_v100": "Design",
            "front_head_v100": "B",
            "shell_type_v100": "E",
            "rear_head_v100": "M",
            "thermo_package_v100": "Ideal mixture",
            "flow_arrangement_v100": "Counter-current",
            "hot_stream_definition": "Pure fluid",
            "hot_fluid_v100": "Water",
            "hot_tin_v100": 90.0,
            "hot_p_v100": 4.0,
            "hot_flow_v100": 5.0,
            "hot_tout_v100": 60.0,
            "cold_stream_definition": "Pure fluid",
            "cold_fluid_v100": "Water",
            "cold_tin_v100": 25.0,
            "cold_p_v100": 3.0,
            "cold_flow_v100": 7.0,
            "shell_id_v100": 0.65,
            "tube_od_mm_v100": 19.05,
            "tube_id_mm_v100": 15.75,
            "tube_length_v100": 5.0,
            "tube_count_v100": 300,
            "tube_passes_v100": 2,
            "tube_pitch_mm_v100": 25.0,
            "tube_layout_v100": "triangular",
            "baffle_count_v100": 10,
            "baffle_cut_v100": 25,
        },
    },
    "Thermal Oil / Water Heater": {
        "description": "Higher-temperature sensible service with thermal oil on the hot side.",
        "ui_state": {
            "mode_v100": "Design",
            "front_head_v100": "B",
            "shell_type_v100": "E",
            "rear_head_v100": "U",
            "thermo_package_v100": "Ideal mixture",
            "flow_arrangement_v100": "Counter-current",
            "hot_stream_definition": "Pure fluid",
            "hot_fluid_v100": "Thermal oil",
            "hot_tin_v100": 180.0,
            "hot_p_v100": 5.0,
            "hot_flow_v100": 4.0,
            "hot_tout_v100": 130.0,
            "cold_stream_definition": "Pure fluid",
            "cold_fluid_v100": "Water",
            "cold_tin_v100": 35.0,
            "cold_p_v100": 4.0,
            "cold_flow_v100": 5.5,
            "shell_id_v100": 0.75,
            "tube_od_mm_v100": 19.05,
            "tube_id_mm_v100": 15.75,
            "tube_length_v100": 6.0,
            "tube_count_v100": 360,
            "tube_passes_v100": 2,
            "tube_pitch_mm_v100": 25.0,
            "tube_layout_v100": "triangular",
            "baffle_count_v100": 12,
            "baffle_cut_v100": 25,
        },
    },
    "Compact Stainless Screening": {
        "description": "Compact geometry/material starting point for clean corrosive service screening.",
        "ui_state": {
            "mode_v100": "Design",
            "front_head_v100": "A",
            "shell_type_v100": "E",
            "rear_head_v100": "S",
            "thermo_package_v100": "Ideal mixture",
            "flow_arrangement_v100": "Counter-current",
            "hot_stream_definition": "Pure fluid",
            "hot_fluid_v100": "Ethanol",
            "hot_tin_v100": 110.0,
            "hot_p_v100": 6.0,
            "hot_flow_v100": 2.5,
            "hot_tout_v100": 65.0,
            "cold_stream_definition": "Pure fluid",
            "cold_fluid_v100": "Water",
            "cold_tin_v100": 20.0,
            "cold_p_v100": 5.0,
            "cold_flow_v100": 7.0,
            "shell_id_v100": 0.55,
            "tube_od_mm_v100": 15.88,
            "tube_id_mm_v100": 12.80,
            "tube_length_v100": 5.0,
            "tube_count_v100": 360,
            "tube_passes_v100": 4,
            "tube_pitch_mm_v100": 20.0,
            "tube_layout_v100": "triangular",
            "baffle_count_v100": 12,
            "baffle_cut_v100": 25,
            "mech_shell_material_v100": "316L stainless steel (screening)",
            "mech_tube_material_v100": "316L stainless steel (screening)",
        },
    },
}


def preset_names() -> list[str]:
    return list(PRESETS)


def get_preset(name: str) -> dict:
    if name not in PRESETS:
        raise ValueError(f"Unknown HX//RACE preset '{name}'.")
    return deepcopy(PRESETS[name])
